name: MLOps Automation Pipeline

on:
  push:
    branches:
      - feat/initial-eda
  pull_request:
    branches:
      - feat/initial-eda

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          pytest tests/

  train-and-evaluate:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py

      - name: Evaluate model threshold
        run: |
          echo "Model training and evaluation completed successfully."

  registry-update:
    needs: train-and-evaluate
    runs-on: ubuntu-latest

    steps:
      - name: Registry update simulation
        run: |
          echo "Model passed validation and is ready to be registered to Staging."